builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  ignore:
    - goos: darwin
      goarch: 386
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-PREVIEW"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
